version: '3.8'

services:
  frontend-webyavirac: 
    image: webyavirac:latest
    networks:
      - traefik-public
    deploy:
      labels:     
        - "traefik.enable=true"
        - "traefik.http.routers.webyavirac.entrypoints=http"
        - "traefik.http.routers.webyavirac.rule=Host(`webyavirac.sistemaagil.net`)"
        - "traefik.http.middlewares.webyavirac-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.webyavirac.middlewares=webyavirac-https-redirect"
        - "traefik.http.routers.webyavirac-secure.entrypoints=https"
        - "traefik.http.routers.webyavirac-secure.rule=Host(`webyavirac.sistemaagil.net`)"
        - "traefik.http.routers.webyavirac-secure.tls=true"
        - "traefik.http.routers.webyavirac-secure.tls.certresolver=http"
        - "traefik.http.routers.webyavirac-secure.service=webyavirac"
        - "traefik.http.services.webyavirac.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"	
networks:
  traefik-public:
    external: true
  tendencias-networks:
    external: true