version: '3.8'

services:
  frontend-webyavirac: 
    image: webyavirac:latest
    networks:
      - traefik-public
      - webyavirac-networks
    deploy:
      labels:     
        - "traefik.enable=true"
        - "traefik.http.routers.webyavirac.entrypoints=http"
        - "traefik.http.routers.webyavirac.rule=Host(`webyavirac.sistemaagil.net`)"
        - "traefik.http.middlewares.webyavirac-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.webyavirac.middlewares=webyavirac-https-redirect"
        - "traefik.http.routers.webyavirac-secure.entrypoints=https"
        - "traefik.http.routers.webyavirac-secure.rule=Host(`webyavirac.sistemaagil.net`)"
        - "traefik.http.routers.webyavirac-secure.tls=true"
        - "traefik.http.routers.webyavirac-secure.tls.certresolver=http"
        - "traefik.http.routers.webyavirac-secure.service=webyavirac"
        - "traefik.http.services.webyavirac.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"			

  backend-webyavirac:
    image: backend-webyavirac:latest
    networks:
      - webyavirac-networks
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend-webyavirac.entrypoints=http"
        - "traefik.http.routers.backend-webyavirac.rule=Host(`backend-webyavirac.sistemaagil.net`)"
        - "traefik.http.middlewares.backend-webyavirac-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.backend-webyavirac.middlewares=backend-webyavirac-https-redirect"
        - "traefik.http.routers.backend-webyavirac-secure.entrypoints=https"
        - "traefik.http.routers.backend-webyavirac-secure.rule=Host(`backend-webyavirac.sistemaagil.net`)"
        - "traefik.http.routers.backend-webyavirac-secure.tls=true"
        - "traefik.http.routers.backend-webyavirac-secure.tls.certresolver=http"
        - "traefik.http.routers.backend-webyavirac-secure.service=backend-webyavirac"
        - "traefik.http.services.backend-webyavirac.loadbalancer.server.port=3000"
        - "traefik.docker.network=traefik-public"

  basededatos-pg:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: r6qJMCocTNQdHXQyCMhW
    networks:
      - webyavirac-networks	

networks:
  traefik-public:
    external: true
  webyavirac-networks:
    external: true